### ISSUE TITLE
About usage

### ISSUE THREAD

**Issue by fnaith** [Mantas-2155X/StudioPOV#2]
What does `Select a character in the object picker` mean?

**Comment by Mantas-2155X** [comment]
Hello,
it means you click on the character in the Workspace window to select it.
![2020-06-17_17-53](https://user-images.githubusercontent.com/13873974/84913770-8d107a00-b0c3-11ea-95ac-13bfcb7f1afc.png)

**Comment by fnaith** [comment]
Thanks! I am so silly lol

**Comment by fnaith** [comment]
Is this plugin studio only?

**Comment by Mantas-2155X** [comment]
Yes, it's called `StudioPOV` for a reason, it's also written in the description that the plugin is for the studio.

**Comment by fnaith** [comment]
Understand, thanks~
